<%@ Page Title="" Language="C#" AutoEventWireup="true" CodeBehind="ViewFile.aspx.cs"
    Inherits="SIS.Pages.ViewFile" MasterPageFile="~/Site.Master" EnableEventValidation="false" %>

<%@ Register Src="~/HelperClass/MultiCheckCombo.ascx" TagName="MultiCheckCombo" TagPrefix="uc1" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">


    <link href="../Styles/jquery.ui.all.css" rel="stylesheet" type="text/css" />
    <link href="../Styles/demos.css" rel="stylesheet" type="text/css" />
    <script src="../Scripts/MainPage.js" type="text/javascript"></script>
    <script src="../Scripts/jquery-1.6.1.min.js" type="text/javascript"></script>
    <script src="../Scripts/jquery.ui.core.js" type="text/javascript"></script>
    <script src="../Scripts/jquery.ui.widget.js" type="text/javascript"></script>
    <script src="../Scripts/jquery.ui.datepicker.js" type="text/javascript"></script>
    <script src="../Scripts/jquery.ui.datepicker-en-GB.js" type="text/javascript"></script>
    <script type="text/javascript">
       
    </script>
    <div>
        <table>
            <tr>
                <td>
                    <asp:Label ID="Label1" runat="server" Text="Tag"></asp:Label>
                </td>
                <td>
                    <asp:TextBox ID="txttag" runat="server"></asp:TextBox></td>
            </tr>
        </table>
        <table>
            <tr>
                <td>
                    <asp:FileUpload ID="fudocs" runat="server" class="btn btn-medium btn-primary" />
                </td>
                <td>
                    <asp:Button ID="btnupload" runat="server" Text="Upload" OnClick="btnupload_Click" class="btn btn-medium btn-primary" /></td>
            </tr>
        </table>
    </div>
    <br />
    <br />
    <div>
        <asp:GridView ID="grdfiles" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
            CellPadding="4" ForeColor="#333333" DataKeyNames="Id" OnRowDeleting ="dlresultlist_RowDeleting"
            GridLines="None">
            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
            <Columns>
                <asp:TemplateField HeaderText="View">
                    <ItemTemplate>
                        <asp:HyperLink ID="lnkView" runat="server" NavigateUrl='<%# Eval("Id", "DownloadFile.aspx?Id={0}") %>' Text="View"></asp:HyperLink>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:BoundField DataField="Tag" HeaderText="Tag" SortExpression="Tag" />
                <asp:BoundField DataField="DateCreated" HeaderText="DateCreated" ReadOnly="True" SortExpression="DateCreated" />
                <asp:BoundField DataField="ContentType" HeaderText="ContentType" ReadOnly="True" SortExpression="ContentType" />
                <asp:BoundField DataField="OriginalName" HeaderText="OriginalName" ReadOnly="True" SortExpression="OriginalName" />
            </Columns>
            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />


            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#E9E7E2" />
            <SortedAscendingHeaderStyle BackColor="#506C8C" />
            <SortedDescendingCellStyle BackColor="#FFFDF8" />
            <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
        </asp:GridView>


    </div>
</asp:Content>
